[build]
  command = "npm run build"
  publish = "dist"                      
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "20"
  SERVER_PRESET = "netlify"
  NITRO_PRESET = "netlify"
